name: mega-linter-helmfile

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  mega-linter-helmfile:
    name: mega-linter-helmfile
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Commit"
        uses: actions/checkout@v2
      - name: "Lint Helmfiles"
        uses: cloudposse/actions/github/mega-linter@5430fa5
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            PLUGINS: "https://raw.githubusercontent.com/cloudposse/actions/helmfile-mega-linter/github/mega-linter/mega-linter-plugin-helmfile/helmfile.megalinter-descriptor.yml"
